id: PC358C432
initial_creation_type: ocr
source_metadata:
  volumes:
    a5cad138b12c4309bd41bb7b76e2ff35:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: སེང་ལྡེང་ནགས་ཀྱི་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
